blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/almguru/build-templates/blob/main/.github/BRANCH_NAMING.md
    about: Learn about our branch naming conventions and contribution guidelines
  - name: 💬 Discussions
    url: https://github.com/almguru/build-templates/discussions
    about: Ask questions and discuss ideas with the community
